name: Build For Apple
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-mac:
    name: Build for Apple
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        target: [iOS, ""]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: "15.2"
      - name: Configure
        run: |
          mkdir build && cd build
          cmake -G "Xcode" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DSDL_STATIC=ON -DSDL_SHARED=OFF ..
      - name: Build
        run: cmake --build build --target install --config Release

      - name: Create DMG
        run: |
          cd build
          hdiutil create -size 2g -srcfolder release -volname q14_apple_${{ matrix.target }} q14_apple_${{ matrix.target }}.dmg
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: q14-apple-${{ matrix.target }}
          path: build/*.dmg
