name: Build Sample
on: [push, pull_request]

jobs:
    build-win:
        name: Build for Windows
        runs-on: windows-latest
        strategy:
          fail-fast: false
          matrix:
              arch: [x64, ARM64]
              target: [Windows]

        steps:
          - uses: actions/checkout@v4
            with:
                submodules: true
          - name: Configure
            run: | 
                mkdir build && cd build
                cmake -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DCMAKE_SYSTEM_VERSION="10.0" -A${{ matrix.arch }} ..
          - name: Build
            run: cmake --build build --target sdl-min --config Release
          - name: Upload Build
            uses: actions/upload-artifact@v3
            with: 
                name: sdl-min-${{ matrix.target }}-${{ matrix.arch }}
                path: |
                    build/Release/*.exe
                    build/Release/*.dll

    build-mac:
        name: Build for macOS
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v4
            with:
                submodules: true
          - name: Configure
            run: | 
                mkdir build && cd build
                cmake -G "Xcode" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO ..
          - name: Build
            run: cmake --build build --target install --config Release

          - name: Create DMG
            run: | 
                cd build
                hdiutil create -size 2g -srcfolder release -volname sdl_min_mac sdl_min_mac.dmg
          - name: Upload Build
            uses: actions/upload-artifact@v3
            with: 
                name: sdl-min-mac
                path: build/*.dmg